// Arabic text of the film (approved by the client). Keys are the English strings exactly as the scenes
// write them; "|" breaks lines (same count as the English, so the per-line reveals keep their cues) and
// [..] marks the rose-gold words. Short keys also translate labels inside the film's own UI panels.
// ZOOD is always written زود.
const AR = {
  // opening
  'Luxury.': 'الرفاهية.',
  'It has always been at the heart of [ZOOD.]': 'دائمًا كانت في قلب [زود.]',
  'But luxury in every [detail.]': 'لكن الرفاهية في كل [التفاصيل.]',
  '[More] presence.': '[زود] في الوجود،',
  '[More] living.': '[زود] في العيش،',
  '[More]|personalization.': '[زود]|في التفصيل،',
  '[More]': '[زود]',
  'comfort.': 'في راحتك،',
  '[More] time for what truly matters.': '[وزود] في وقتك لما يهمك.',
  'Because true luxury is not|about having more things.': 'لأن الرفاهية الحقيقية|ليست في كثرة الأشياء،',
  'It is about having more of|[what is designed around you.]': 'بل في الحصول على الزود|[فيما يُصنع لك.]',
  'And that is exactly what': 'وهذا بالضبط معنى',
  'happiness': 'السعادة.',
  '[means.]': '',
  'That is why, at [ZOOD,]|luxury is not a promise|on paper.': 'لذلك في [زود،]|الرفاهية ليست وعدًا|على الورق،',
  'It is an experience|[you live.]': 'بل تجربة|[تُعاش.]',
  // traditionally
  'Traditionally, owning a property meant…': 'كان التملّك تقليديًا يعني…',
  'Paperwork.': 'أوراقًا،',
  'Spreadsheets.': 'وجداول،',
  'Conversations.': 'ومحادثات،',
  'Endless steps.': 'وخطوات لا تنتهي.',
  'But what if the entire journey|could come together in [one place?]': 'لكن ماذا لو اجتمعت|الرحلة كلها في [مكان واحد؟]',
  'We build [communities.]': 'نحن نبني [المجتمعات.]',
  'And today, we have built with you': 'واليوم بنينا معك وسيلة أذكى',
  'A smarter way to': 'طريقة',
  '[Discover.]': '[لتكتشف.]', '[Create.]': '[لتبتكر.]', '[Live.]': '[لتعيش.]', '[Enjoy.]': '[لتستمتع.]',
  'Four [journeys.]': 'أربع [رحلات،]',
  'Not four applications.': 'ليست أربعة تطبيقات،',
  '[One] application.': 'بل تطبيق [واحد.]',
  // discover
  'This is|the [ZOOD] app.': 'هذا هو|تطبيق [زود.]',
  'Explore every destination|[with complete clarity.]': 'استكشف كل وجهات زود|[بوضوح تام.]',
  'The layouts,|the views,|and the neighborhood|[around you.]': 'المخططات،|والإطلالات،|والحي|[من حولك.]',
  'Then tap,|rotate the model,|choose your unit,|and walk through|[your environment.]': 'ثم اضغط،|أدر المجسّم،|اختر وحدتك،|وتجوّل|[في بيئتك.]',
  'Before the first foundation|stone is even laid,': 'قبل أن يوضع|حجر الأساس الأول،',
  'See the available units|[in real time.]': 'شاهد الوحدات المطروحة|[لحظيًا.]',
  'Live · 95 units available': 'مباشر · 95 وحدة متاحة',
  'Compare them|[side by side.]': 'قارن بينها|[جنبًا إلى جنب.]',
  'Filter by': 'وفلتر حسب',
  'Space': 'المساحة', 'Distance': 'المسافة', 'Family': 'عائلية', 'Individual': 'فردية', 'Residential community': 'بيئتك السكنية',
  'So you can find|your [perfect home,]': 'لتصل إلى|بيت [أحلامك،]',
  'not just an empty room.': 'لا إلى غرفة فارغة.',
  // create
  'Verify your identity|[in seconds.]': 'تحقّق من هويتك|[خلال ثوانٍ.]',
  'Request information.|Book a dedicated visit.|[And reserve your unit.]': 'اطلب المعلومات،|احجز زيارة مخصصة،|[واحجز وحدتك.]',
  'Information requested': 'تم طلب المعلومات',
  'Visit booked · Thu 10:00 AM': 'تم حجز الزيارة · الخميس 10:00 ص',
  'Review your contract.': 'راجع عقدك،',
  'Then sign it digitally|and [securely.]': 'ثم وقّعه رقميًا|[وبأمان.]',
  'With a single platform,|[ZOOD] keeps everything with you.': 'بمنصة واحدة،|[زود] معك في كل شيء.',
  'Every payment.|Every stage.|Every update.': 'في كل دفعة،|كل مرحلة،|كل تحديث.',
  'Update · Milestone 8 · Facade complete · due in 39 days': 'تحديث · المرحلة 8 · اكتمال الواجهة · بعد 39 يومًا',
  'CONSTRUCTION PROGRESS': 'تقدّم البناء',
  'Track the progress|of [construction.]': 'تابع تقدّم|[الأعمال.]',
  'Access [reports.]': 'اطّلع على [التقارير.]',
  'Monthly report · PDF': 'التقرير الشهري · PDF',
  'Watch your project take shape|through [live updates.]': 'وشاهد مشروعك يتشكّل|من خلال [البث المباشر.]',
  'Level 14 · Slab poured today': 'الطابق 14 · صبّ السقف اليوم',
  // handover
  'When it is time for [handover,]|we take care of the details.': 'وعند [الاستلام،]|نهتم نحن بالتفاصيل.',
  'Licenses': 'التراخيص', 'Documentation': 'التوثيق', 'Keys handed over': 'تسليم المفاتيح',
  'You simply enjoy|the [moment.]': 'استمتع أنت|[باللحظة،]',
  'While [ZOOD] takes care of the rest.': '[وزود] يتولى الباقي.',
  // live
  'Your home.|Your property.': 'سكنك،|ملكيتك،',
  'Everything that matters to you,|[protected securely]|and managed seamlessly.': 'وكل ما يهمك،|[محفوظ بأمان]|ومُدار بسلاسة.',
  'And everything your community|brings together, in [one place.]': 'وكل ما يجمعه مجتمعك،|في [مكان واحد.]',
  'presence.': 'في الوجود،', 'connection.': 'في التواصل،', 'efficiency.': 'في الفاعلية،', 'possibilities|for the community.': 'في إمكانيات|المجتمع.',
  'Everything you need,|[whenever you need it.]': 'كل ما تحتاجه،|[وقتما تحتاجه.]',
  'As if [ZOOD] is|always with you.': 'وكأن [زود]|دائمًا معك،',
  'Day': 'ليلًا', '[and night.]': '[أو نهارًا.]',
  // enjoy
  'For those who invest|in what we build,|[there is something more.]': 'ولمن يستثمر|فيما نبنيه،|[هناك شيء آخر.]',
  'A smarter way to make|your property [work for you.]': 'طريقة أذكى|ليعمل عقارك [لصالحك.]',
  'Long-term leasing.': 'تأجير طويل،', 'Short stays.': 'إقامات قصيرة،', 'Or selling.': 'أو بيع.',
  'You choose in seconds.': 'أنت تختار في ثوانٍ،', '[ZOOD] takes care of the rest.': '[وزود] تتولى الباقي.',
  // finale
  'Discover.': 'اكتشف،', 'Enjoy.': 'استمتع،', 'Live.': 'عش،', '[Dwell.]': '[اسكن.]',
  'Designed for the rhythm|of modern life.': 'صُمّم لإيقاع|الحياة العصرية.',
  'Because after construction,|[responsibility begins.]': 'ما بعد البناء،|[تبدأ المسؤولية.]',
  'Live luxury.  Live [ZOOD.]': 'عش الرفاهية.  عش [زود.]',
  'DOWNLOAD THE ZOOD APP': 'حمّل تطبيق زود',
};
// chapter labels (01 Discover …) use the verbs, not the "a smarter way to …" forms above
const AR_CHAPTER = { Discover: 'اكتشف', Create: 'ابتكر', Live: 'عش', Enjoy: 'استمتع' };
// labels inside the film's own UI panels (compare / filter cards, packages screens, payment path, finale)
const AR_UI = {
  'ZOOD': 'زود', 'LIVE': 'مباشر',
  'Unit A4': 'الوحدة A4', 'Unit B7': 'الوحدة B7', 'Floor': 'الطابق', 'Bedrooms': 'غرف النوم', 'Built-up area': 'المساحة المبنية', 'Price': 'السعر',
  'SAR 1,200,000': '1,200,000 ر.س', 'SAR 1,100,000': '1,100,000 ر.س',
  'Area': 'المساحة', 'Sq. Ft.': 'قدم²', 'Bathrooms': 'دورات المياه', 'Schools': 'مدارس', 'Parks': 'حدائق', 'Shops': 'متاجر',
  'Radius': 'النطاق', 'KM': 'كم', 'Studio': 'استوديو', 'Pet-friendly': 'يسمح بالحيوانات', 'Gym': 'نادٍ رياضي',
  'Furniture Packages': 'باقات الأثاث', 'Unit A4 · Wadi Residence': 'الوحدة A4 · وادي ريزيدنس',
  'Bedroom': 'غرفة النوم', 'Living': 'المعيشة', 'Dining': 'الطعام', 'Kitchen': 'المطبخ',
  'STYLE 1 OF 3': 'الطراز 1 من 3', 'STYLE 2 OF 3': 'الطراز 2 من 3', 'STYLE 3 OF 3': 'الطراز 3 من 3',
  'Classic': 'كلاسيك', 'Contemporary': 'معاصر', 'Luxury': 'فاخر',
  'Carved mahogany, damask and brass, with a canopy bed and crystal chandelier.': 'خشب ماهوجني منحوت، ودمسق ونحاس، مع سرير بمظلة وثريا كريستال.',
  'Oak slats, linen and warm concrete, with soft curved seating and warm lighting.': 'شرائح البلوط، والكتان، والخرسانة الدافئة، مع جلسات منحنية ناعمة وإضاءة دافئة.',
  'Emerald velvet, walnut panelling and polished brass, with a crowned canopy.': 'مخمل زمردي، وألواح الجوز، ونحاس مصقول، مع مظلة متوّجة.',
  '12 pieces · 4 rooms · excl. VAT': '12 قطعة · 4 غرف · غير شامل الضريبة', '15 pieces · 4 rooms · excl. VAT': '15 قطعة · 4 غرف · غير شامل الضريبة',
  '12 pieces · excl. VAT': '12 قطعة · غير شامل الضريبة', '15 pieces · excl. VAT': '15 قطعة · غير شامل الضريبة',
  'Artwork': 'لوحة فنية', 'Lamps': 'مصابيح', 'Lounge chair': 'كرسي استرخاء', 'Nightstands ×2': 'طاولتا سرير ×2', 'King bed': 'سرير كينج', 'Wool rug': 'سجادة صوف',
  'Tap a tag to see the piece': 'اضغط على البطاقة لرؤية القطعة', 'Master bedroom · 6 pieces': 'غرفة النوم الرئيسية · 6 قطع',
  'Package total': 'إجمالي الباقة', 'incl. VAT · delivery & installation included': 'شامل الضريبة · التوصيل والتركيب مشمولان',
  'Add Contemporary to my selection': 'أضف معاصر إلى اختياري', 'Added to my selection': 'تمت الإضافة إلى اختياري',
  'Booking': 'الحجز', 'Deposit': 'الدفعة المقدمة', 'Excavation': 'الحفر', 'Foundation': 'الأساسات', 'Structure 50%': 'الهيكل 50%',
  'Structure complete': 'اكتمال الهيكل', 'Facade start': 'بدء الواجهة', 'Facade complete': 'اكتمال الواجهة', 'Interior finishing': 'التشطيبات الداخلية',
  'MEP & landscaping': 'الأنظمة والتنسيق', 'Final inspection': 'الفحص النهائي', 'Handover': 'التسليم',
  'Paid': 'مدفوعة', 'Due 15 Nov': 'تستحق 15 نوفمبر', 'Feb 2027': 'فبراير 2027', 'Apr 2027': 'أبريل 2027', 'Q2 2027': 'الربع الثاني 2027',
  'PAID TO DATE': 'المدفوع حتى الآن', 'SAR': 'ر.س', 'of SAR 1,200,000 total': 'من إجمالي 1,200,000 ر.س', 'of 12 milestones paid': 'من 12 مرحلة مدفوعة',
  'Progress:': 'التقدّم:', '% Complete': '% مكتمل', 'Construction': 'البناء', 'Tracked live': 'متابعة مباشرة', 'Average yield': 'متوسط العائد',
};
for (let i = 1; i <= 12; i++) AR_UI['MILESTONE ' + i] = 'المرحلة ' + i;
